#!/bin/bash
# 
# libaxol-term: a library written in shell to create interfaces.
# Use it with source.
#
# libaxol-term needs this programs to work: bash, tput, stty, and bc.
# You can obtain needed programs with the follow packages: gnu coreutils, termutils, bash and bc.
# !! NOT TESTED !! Or you can obtain it with busybox multibinary (you need to install bash and tput to work with this library).
#

# MAIN FUNCTIONS
function libaxolterm_init() {
	tput civis
	stty -echo
	clear
}

function libaxolterm_getsize() {
	read -r LIBAXOLTERM_TERM_Y LIBAXOLTERM_TERM_X < <(stty size)
}

function libaxolterm_getsize_calc() {
	read -r LIBAXOLTERM_TERM_CALC_Y LIBAXOLTERM_TERM_CALC_X < <(stty size)
}

function libaxolterm_getsize_refresh() {
	read -r LIBAXOLTERM_TERM_REFRESH_Y LIBAXOLTERM_TERM_REFRESH_X < <(stty size)
}

function libaxolterm_calc() {
	libaxolterm_getsize_calc
	LIBAXOLTERM_CORD_Y=$(echo "scale=2; ${1} * ${LIBAXOLTERM_TERM_CALC_Y}" | bc -l )
	LIBAXOLTERM_CORD_X=$(echo "scale=2; ${2} * ${LIBAXOLTERM_TERM_CALC_X}" | bc -l )
}

function libaxolterm_goto() {
	tput cup ${1%.*} ${2%.*}
}

function libaxolterm_refresh() {
	if [ "$LIBAXOLTERM_TERM_REFRESH_X" != "$LIBAXOLTERM_TERM_X" ] || [ "$LIBAXOLTERM_TERM_REFRESH_Y" != "$LIBAXOLTERM_TERM_Y" ]; then
		clear
	fi
}

function libaxolterm_writetext() {
	libaxolterm_calc $1 $2
	LIBAXOLTERM_WRITETEXT_NUM=${#3}
	read -r LIBAXOLTERM_WRITETEXT_CENTER < <(echo $((LIBAXOLTERM_WRITETEXT_NUM / 2 )) )
	read -r LIBAXOLTERM_WRITETEXT_FIX < <(echo $(( ${LIBAXOLTERM_CORD_X%.*} - LIBAXOLTERM_WRITETEXT_CENTER)) )
	libaxolterm_goto $LIBAXOLTERM_CORD_Y $LIBAXOLTERM_WRITETEXT_FIX 
	echo "$3"
}

function libaxolterm_writetext_notcentered() {
	libaxolterm_calc $1 $2
	libaxolterm_goto $LIBAXOLTERM_CORD_Y $LIBAXOLTERM_CORD_X
	echo "$3"
}

function libaxolterm_exit() {
	tput cnorm
	stty echo
	clear
}
